library:
  source-dirs: src
tests:
  DiscordBot-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiscordBot
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
- split
- directory
- http-types
- http-client-tls
- yaml
- bytestring
- http-client
- HTTP
- http-conduit
- aeson
- text
- base >= 4.7 && < 5
name: DiscordBot
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/DiscordBot
license: BSD3
executables:
  DiscordBot-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DiscordBot
description: Please see the README on GitHub at <https://github.com/githubuser/DiscordBot#readme>
